[keys.normal]
"h" = "back"
"l" = "enter"
"j" = "down"
"k" = "up"
"gg" = "top"
"G" = "bottom"
"d" = "delete"
"y" = "yank"
"p" = "paste"
"a" = "create"
"r" = "rename"
"u" = "undo"
"ctrl+r" = "redo"
"ctrl+q" = "quit"
"zh" = "toggle_hidden"
